  version: 0.2

  env:
    variables:
      hugo_version: "0.84.4"

  phases:
    install:
      commands:
        - wget "https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_${hugo_version}_Linux-64bit.deb"
        - dpkg -i hugo_${hugo_version}_Linux-64bit.deb
      finally:
        - hugo version
    build:
      commands:
        - hugo
        - cd public
        - aws s3 sync . s3://deepdiveshugowebsite --delete
      finally:
        - echo "Build script finished running"