  version: 0.2

  env:
    variables:
      hugo_version: "0.84.4"

  phases:
    build:
      commands:
        - hugo
        - cd public
        - aws s3 sync . s3://deepdiveshugowebsite --delete
      finally:
        - echo "Build script finished running"